<template>
  <view class="page"><view class="head"><text class="step">{{ step }}/3</text><text class="title">{{ title }}</text><text class="sub">{{ subtitle }}</text></view>
    <view v-if="step===1" class="panel"><text class="label">以下任一情况请选择“有”</text><view v-for="item in risks" :key="item.key" class="risk"><text>{{ item.label }}</text><switch :checked="eligibility[item.key]" color="#49bd8b" @change="onRiskChange(item.key, $event)" /></view></view>
    <view v-else-if="step===2" class="panel"><text class="label">每天吃几餐</text><picker :range="mealOptions" @change="onMealCount"><view class="input">{{ preferences.meal_count }} 餐</view></picker><text class="label">饮食偏好</text><picker :range="cuisineLabels" @change="onCuisine"><view class="input">{{ cuisineLabels[cuisineValues.indexOf(preferences.cuisine_preference)] }}</view></picker><text class="label">进食时间窗（16:8 必填）</text><view class="time-row"><input v-model="preferences.eating_window_start" class="input" placeholder="10:00" /><text>至</text><input v-model="preferences.eating_window_end" class="input" placeholder="18:00" /></view></view>
    <view v-else class="panel"><text class="program">{{ codeLabel }}</text><text class="label">每日目标热量</text><input v-model.number="calories" type="number" class="input" /><text class="hint">请依据个人资料、训练量与专业建议填写。532 会锁定蛋白质和脂肪，仅在后续确认后调整碳水。</text></view>
    <view class="bottom"><button v-if="step>1" class="ghost" @tap="step--">上一步</button><button class="primary" @tap="next">{{ step===3 ? '创建并确认方案' : '继续' }}</button></view>
  </view>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'; import { onLoad } from '@dcloudio/uni-app'; import { dietProgramApi, type DietProgramCode, type EligibilityPayload } from '@/api/diet-programs';
const code = ref<DietProgramCode>('balanced_cut'); const step=ref(1); const calories=ref(1800); const mealOptions=[2,3,4,5,6]; const cuisineLabels=['家常中餐','轻食优先','外卖优先']; const cuisineValues=['home_chinese','light_meal','takeout'] as const;
const eligibility=ref<EligibilityPayload>({under_18:false,pregnant_or_breastfeeding:false,diabetes:false,serious_liver_kidney_gallbladder:false,eating_disorder_history:false});
const preferences=ref({meal_count:3,allergens:[] as string[],vegetarian_type:'none' as const,avoid_foods:[] as string[],eating_window_start:'10:00',eating_window_end:'18:00',budget_level:'medium' as const,cooking_setup:'full_kitchen' as const,cuisine_preference:'home_chinese' as typeof cuisineValues[number]});
const risks=[{key:'under_18' as const,label:'未满 18 岁'},{key:'pregnant_or_breastfeeding' as const,label:'孕期或哺乳期'},{key:'diabetes' as const,label:'糖尿病'},{key:'serious_liver_kidney_gallbladder' as const,label:'严重肝、肾或胆囊疾病'},{key:'eating_disorder_history' as const,label:'进食障碍史'}];
const names:Record<DietProgramCode,string>={balanced_cut:'均衡减脂',time_restricted_16_8:'16:8 轻断食',carb_taper_532:'532 碳水渐降',ketogenic:'生酮饮食'}; const codeLabel=computed(()=>names[code.value]); const title=computed(()=>step.value===1?'先做安全筛查':step.value===2?'告诉我你的饮食偏好':'确认初始目标'); const subtitle=computed(()=>step.value===1?'不符合条件时，我们只提供普通记录功能。':step.value===2?'这些限制会直接用于生成菜单。':'创建后可在菜单中替换食物。');
onLoad((o:any)=>{ if (o.code && o.code in names) code.value=o.code; });
function onMealCount(event: any) { preferences.value.meal_count = Number(event.detail.value) + 2; }
function onCuisine(event: any) { preferences.value.cuisine_preference = cuisineValues[Number(event.detail.value)]; }
function onRiskChange(key: keyof EligibilityPayload, event: any) { eligibility.value[key] = Boolean(event.detail.value); }
async function next(){ if(step.value===1 && Object.values(eligibility.value).some(Boolean)){uni.showModal({title:'暂不适合自动方案',content:'你仍可使用普通饮食记录；请咨询医生或营养师。',showCancel:false});return;} if(step.value<3){step.value++;return;} try{uni.showLoading({title:'创建中'});await dietProgramApi.savePreferences(preferences.value);const created=await dietProgramApi.create({template_code:code.value,calories_kcal:calories.value,macro_ratio:'532',activity_level:'light',target_loss_rate:.005,eligibility:eligibility.value});await dietProgramApi.confirm(created.id);uni.redirectTo({url:`/pages/diet/meal-plan?programId=${created.id}&name=${encodeURIComponent(codeLabel.value)}`});}catch(e:any){uni.showToast({title:e?.message||'创建失败，请先补全个人资料',icon:'none'});}finally{uni.hideLoading();}}
</script>
<style scoped lang="scss">.page{min-height:100vh;padding:42rpx 30rpx;background:#f6fbf8}.head{display:flex;flex-direction:column;gap:12rpx;margin-bottom:36rpx}.step{color:#35a875;font-size:24rpx;font-weight:700}.title{font-size:46rpx;font-weight:800;color:#20342b}.sub,.hint{color:#738078;font-size:26rpx;line-height:1.55}.panel{background:#fff;border-radius:28rpx;padding:30rpx;display:flex;flex-direction:column;gap:24rpx}.label{font-size:28rpx;font-weight:650;color:#314239}.risk{display:flex;align-items:center;justify-content:space-between;font-size:29rpx;color:#34443c;padding-bottom:18rpx;border-bottom:1rpx solid #eef2ef}.input{min-height:84rpx;line-height:84rpx;padding:0 22rpx;border-radius:16rpx;background:#f3f8f5;color:#24362e;font-size:28rpx;flex:1}.time-row{display:flex;align-items:center;gap:14rpx;color:#738078}.program{font-size:34rpx;color:#249064;font-weight:750}.bottom{position:fixed;bottom:0;left:0;right:0;padding:24rpx 30rpx calc(24rpx + env(safe-area-inset-bottom));background:#fff;display:flex;gap:18rpx}.primary,.ghost{flex:1;border-radius:18rpx;font-size:30rpx}.primary{background:#42b983;color:#fff}.ghost{background:#edf5f0;color:#39614e}</style>
